version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: mentor_matching_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: mentor_matching_frontend
    ports:
      - "4876:80"
    depends_on:
      - backend
    restart: always
